[project]
name = "damn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "CephasKweku", email = "cephaskweku19@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pandas>=3.0.5",
    "requests>=2.34.2",
    "sqlalchemy>=2.0.52",
]

[project.scripts]
damn = "damn:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
